#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_HOME="$(mktemp -d)"
PORTABILITY_PID=""
WORKSPACE_PID=""
cleanup() {
  if [[ -n "$PORTABILITY_PID" ]] && kill -0 "$PORTABILITY_PID" >/dev/null 2>&1; then
    kill "$PORTABILITY_PID" >/dev/null 2>&1 || true
    wait "$PORTABILITY_PID" >/dev/null 2>&1 || true
  fi
  if [[ -n "$WORKSPACE_PID" ]] && kill -0 "$WORKSPACE_PID" >/dev/null 2>&1; then
    kill "$WORKSPACE_PID" >/dev/null 2>&1 || true
    wait "$WORKSPACE_PID" >/dev/null 2>&1 || true
  fi
  rm -rf "$TEST_HOME"
}
trap cleanup EXIT

# Keep generated bytecode out of the source tree; installers copy directories verbatim.
export PYTHONDONTWRITEBYTECODE=1
export AGENTS_HOME="$TEST_HOME/.agents"
TEST_USER_HOME="$TEST_HOME/user"
mkdir -p "$TEST_USER_HOME"

contains_literal() {
  local needle="$1"
  shift
  if command -v rg >/dev/null 2>&1; then
    rg --fixed-strings -qi -- "$needle" "$@"
  elif command -v grep >/dev/null 2>&1; then
    grep -Fqi -- "$needle" "$@"
  else
    printf 'tests require rg or grep\n' >&2
    exit 1
  fi
}

if [[ "${CI:-}" == true && "${SKIP_PORTABILITY:-0}" == 1 ]]; then
  printf 'CI must run portability tests\n' >&2
  exit 1
fi
if [[ "${CI:-}" == true && "${SKIP_WORKSPACE:-0}" == 1 ]]; then
  printf 'CI must run personal workspace tests\n' >&2
  exit 1
fi

if [[ "${SKIP_PORTABILITY:-0}" != 1 ]]; then
  python3 "$ROOT/tests/test_portability.py" > "$TEST_HOME/portability.log" 2>&1 &
  PORTABILITY_PID=$!
fi

if [[ "${SKIP_WORKSPACE:-0}" != 1 ]]; then
  python3 "$ROOT/tests/test_workspace.py" > "$TEST_HOME/workspace.log" 2>&1 &
  WORKSPACE_PID=$!
fi
python3 "$ROOT/tests/test_catalog_validation.py"
python3 "$ROOT/tests/test_registry.py"
python3 "$ROOT/tests/test_lifecycle.py"
"$ROOT/scripts/agents.sh" library check >/dev/null

PREFLIGHT_AGENTS_HOME="$TEST_HOME/preflight-agents"
PREFLIGHT_USER_HOME="$TEST_HOME/preflight-user"
AGENTS_HOME="$PREFLIGHT_AGENTS_HOME" "$ROOT/scripts/install.sh" \
  --profile software --no-root-files >/dev/null
if HOME="$PREFLIGHT_USER_HOME" AGENTS_HOME="$PREFLIGHT_AGENTS_HOME" \
  "$ROOT/scripts/connect.sh" --host codex --host claude --host gemini --host sourcecraft \
  >/dev/null 2>&1; then
  printf 'missing Foundation preflight unexpectedly succeeded\n' >&2
  exit 1
fi
[[ ! -e "$PREFLIGHT_USER_HOME/.codex" ]]
[[ ! -e "$PREFLIGHT_USER_HOME/.claude" ]]
[[ ! -e "$PREFLIGHT_USER_HOME/.gemini" ]]
[[ ! -e "$PREFLIGHT_USER_HOME/.config" ]]
[[ ! -e "$PREFLIGHT_USER_HOME/.codeassistant" ]]

QUICK_START_AGENTS_HOME="$TEST_HOME/quick-start-agents"
QUICK_START_USER_HOME="$TEST_HOME/quick-start-user"
quick_start_output="$(printf '1,5\ncodex, kimi\ny\n' | \
  HOME="$QUICK_START_USER_HOME" AGENTS_HOME="$QUICK_START_AGENTS_HOME" \
  /bin/bash "$ROOT/scripts/bootstrap.sh")"
if printf '%s\n' "$quick_start_output" | grep -Eiq 'core|profile|foundation'; then
  printf 'interactive setup exposed implementation terminology\n' >&2
  exit 1
fi
grep -qx 'core' "$QUICK_START_AGENTS_HOME/.ecosystem-profiles"
grep -qx 'software' "$QUICK_START_AGENTS_HOME/.ecosystem-profiles"
grep -qx 'video' "$QUICK_START_AGENTS_HOME/.ecosystem-profiles"
[[ -f "$QUICK_START_USER_HOME/.codex/agents/engineer.toml" ]]
[[ -f "$QUICK_START_USER_HOME/.codex/agents/video-producer.toml" ]]
grep -qx 'kimi' "$QUICK_START_AGENTS_HOME/.ecosystem-hosts"

NONINTERACTIVE_AGENTS_HOME="$TEST_HOME/noninteractive-agents"
NONINTERACTIVE_USER_HOME="$TEST_HOME/noninteractive-user"
HOME="$NONINTERACTIVE_USER_HOME" AGENTS_HOME="$NONINTERACTIVE_AGENTS_HOME" \
  /bin/bash "$ROOT/scripts/agents.sh" setup --work code --work video --app codex --app kimi >/dev/null
grep -qx 'core' "$NONINTERACTIVE_AGENTS_HOME/.ecosystem-profiles"
grep -qx 'software' "$NONINTERACTIVE_AGENTS_HOME/.ecosystem-profiles"
grep -qx 'video' "$NONINTERACTIVE_AGENTS_HOME/.ecosystem-profiles"
[[ -f "$NONINTERACTIVE_USER_HOME/.codex/agents/engineer.toml" ]]
grep -qx 'kimi' "$NONINTERACTIVE_AGENTS_HOME/.ecosystem-hosts"

BASH32_AGENTS_HOME="$TEST_HOME/bash32-profile-only-agents"
BASH32_USER_HOME="$TEST_HOME/bash32-profile-only-user"
HOME="$BASH32_USER_HOME" AGENTS_HOME="$BASH32_AGENTS_HOME" \
  /bin/bash "$ROOT/scripts/install.sh" --profile software --no-root-files >/dev/null
grep -qx 'software' "$BASH32_AGENTS_HOME/.ecosystem-profiles"

INVALID_INPUT_AGENTS_HOME="$TEST_HOME/invalid-input-agents"
INVALID_INPUT_USER_HOME="$TEST_HOME/invalid-input-user"
for invalid_host in invalid-host ../codex 'codex;touch' --app; do
  if printf '1\n%s\ny\n' "$invalid_host" | \
    HOME="$INVALID_INPUT_USER_HOME" AGENTS_HOME="$INVALID_INPUT_AGENTS_HOME" \
    "$ROOT/scripts/bootstrap.sh" >/dev/null 2>&1; then
    printf 'unsupported host unexpectedly succeeded: %s\n' "$invalid_host" >&2
    exit 1
  fi
done
[[ ! -e "$INVALID_INPUT_AGENTS_HOME" ]]
[[ ! -e "$INVALID_INPUT_USER_HOME/.codex" ]]

if HOME="$INVALID_INPUT_USER_HOME" AGENTS_HOME="$PREFLIGHT_AGENTS_HOME" \
  "$ROOT/scripts/connect.sh" --host invalid-host --host codex >/dev/null 2>&1; then
  printf 'unsupported direct host unexpectedly succeeded\n' >&2
  exit 1
fi
[[ ! -e "$INVALID_INPUT_USER_HOME/.codex" ]]

HOME="$INVALID_INPUT_USER_HOME" AGENTS_HOME="$INVALID_INPUT_AGENTS_HOME" \
  "$ROOT/scripts/bootstrap.sh" --profile software --dry-run >/dev/null

if printf '1\n\n' | HOME="$INVALID_INPUT_USER_HOME" AGENTS_HOME="$INVALID_INPUT_AGENTS_HOME" \
  "$ROOT/scripts/bootstrap.sh" >/dev/null 2>&1; then
  printf 'interactive setup accepted an empty AI application selection\n' >&2
  exit 1
fi
if HOME="$INVALID_INPUT_USER_HOME" AGENTS_HOME="$INVALID_INPUT_AGENTS_HOME" \
  "$ROOT/scripts/bootstrap.sh" --work code --dry-run >/dev/null 2>&1; then
  printf 'noninteractive setup accepted a missing AI application selection\n' >&2
  exit 1
fi
[[ ! -e "$INVALID_INPUT_AGENTS_HOME" ]]

for invalid_work_pack in 9 ../software '1;touch' --work; do
  if printf '%s\ncodex\ny\n' "$invalid_work_pack" | \
    HOME="$INVALID_INPUT_USER_HOME" AGENTS_HOME="$INVALID_INPUT_AGENTS_HOME" \
    "$ROOT/scripts/bootstrap.sh" >/dev/null 2>&1; then
    printf 'unsupported work pack unexpectedly succeeded: %s\n' "$invalid_work_pack" >&2
    exit 1
  fi
done
[[ ! -e "$INVALID_INPUT_AGENTS_HOME" ]]

CONFLICT_AGENTS_HOME="$TEST_HOME/setup-conflict-agents"
CONFLICT_USER_HOME="$TEST_HOME/setup-conflict-user"
mkdir -p "$CONFLICT_USER_HOME/.codex/skills"
printf 'keep\n' > "$CONFLICT_USER_HOME/.codex/skills/ceo"
if HOME="$CONFLICT_USER_HOME" AGENTS_HOME="$CONFLICT_AGENTS_HOME" \
  "$ROOT/scripts/agents.sh" setup --work code --app codex >/dev/null 2>&1; then
  printf 'host conflict unexpectedly succeeded\n' >&2
  exit 1
fi
[[ ! -e "$CONFLICT_AGENTS_HOME" ]]

[[ -f "$ROOT/README.md" ]]
[[ -f "$ROOT/README.en.md" ]]
[[ -f "$ROOT/README.zh-CN.md" ]]
for forbidden_term in core foundation --profile; do
  if contains_literal "$forbidden_term" "$ROOT/README.md" "$ROOT/README.en.md" "$ROOT/README.zh-CN.md"; then
    printf 'beginner documentation exposed implementation terminology\n' >&2
    exit 1
  fi
done
if contains_literal 'Export portable configuration' "$ROOT/README.en.md"; then
  printf 'English quick start uses unclear recovery terminology\n' >&2
  exit 1
fi
contains_literal './scripts/agents.sh setup' "$ROOT/README.md"
contains_literal 'installation receipt' "$ROOT/README.en.md"
contains_literal 'Save an installation receipt' <("$ROOT/scripts/agents.sh" --help)

ALL_DRY_RUN_HOME="$TEST_HOME/all-dry-run-agents"
HOME="$TEST_HOME/all-dry-run-user" AGENTS_HOME="$ALL_DRY_RUN_HOME" \
  "$ROOT/scripts/agents.sh" setup --work all --app generic --dry-run >/dev/null
"$ROOT/scripts/install.sh" --profile all >/dev/null
"$ROOT/scripts/connect.sh" --host generic >/dev/null
"$ROOT/scripts/doctor.sh" >/dev/null

# The activation registry explains ownership and must never write anything.
REGISTRY_BEFORE="$(python3 "$ROOT/scripts/state.py" hash "$AGENTS_HOME")"
"$ROOT/scripts/agents.sh" registry report >/dev/null
"$ROOT/scripts/agents.sh" registry plan >/dev/null
"$ROOT/scripts/agents.sh" registry reconcile --fail-on-conflict >/dev/null
contains_literal 'skill:natural-writing' <("$ROOT/scripts/agents.sh" registry report)
contains_literal 'wrote nothing' <("$ROOT/scripts/agents.sh" registry plan)
[[ "$(python3 "$ROOT/scripts/state.py" hash "$AGENTS_HOME")" == "$REGISTRY_BEFORE" ]]

# disable withdraws a component and enable puts it back.
"$ROOT/scripts/agents.sh" disable skill:natural-writing >/dev/null
[[ ! -e "$AGENTS_HOME/skills/natural-writing" ]]
[[ -f "$AGENTS_HOME/.disabled/skills/natural-writing/SKILL.md" ]]
contains_literal 'disabled' <("$ROOT/scripts/agents.sh" registry report)
"$ROOT/scripts/agents.sh" enable skill:natural-writing >/dev/null
[[ -f "$AGENTS_HOME/skills/natural-writing/SKILL.md" ]]
[[ ! -e "$AGENTS_HOME/.disabled/skills/natural-writing" ]]

# removal refuses anything this project does not own.
mkdir -p "$AGENTS_HOME/skills/not-ours"
printf '# not ours\n' > "$AGENTS_HOME/skills/not-ours/SKILL.md"
if "$ROOT/scripts/agents.sh" remove not-ours >/dev/null 2>&1; then
  printf 'removal deleted a component this project does not own\n' >&2
  exit 1
fi
[[ -f "$AGENTS_HOME/skills/not-ours/SKILL.md" ]]
rm -rf "$AGENTS_HOME/skills/not-ours"

# removal of an owned component drops it from the manifest too.
"$ROOT/scripts/agents.sh" remove skill:lead-magnet >/dev/null
[[ ! -e "$AGENTS_HOME/skills/lead-magnet" ]]
if grep -qx 'skill:lead-magnet' "$AGENTS_HOME/.ecosystem-installed"; then
  printf 'removal left the component in the installed manifest\n' >&2
  exit 1
fi
"$ROOT/scripts/install.sh" --profile all >/dev/null
[[ -f "$AGENTS_HOME/skills/lead-magnet/SKILL.md" ]]

[[ -f "$AGENTS_HOME/skills/natural-writing/SKILL.md" ]]
[[ -f "$AGENTS_HOME/skills/ceo/SKILL.md" ]]
[[ -f "$AGENTS_HOME/skills/skill-authoring/SKILL.md" ]]
[[ -f "$AGENTS_HOME/skills/campaign-launch/SKILL.md" ]]
[[ -f "$AGENTS_HOME/skills/ui-ux-design/SKILL.md" ]]
[[ -f "$AGENTS_HOME/skills/remotion-video/SKILL.md" ]]
[[ -f "$AGENTS_HOME/skills/context-engineering/SKILL.md" ]]
[[ -f "$AGENTS_HOME/agents/ceo.md" ]]
[[ -f "$AGENTS_HOME/agents/engineer.md" ]]
[[ -f "$AGENTS_HOME/agents/qa-reviewer.md" ]]
[[ -f "$AGENTS_HOME/agents/product-editor.md" ]]
[[ -f "$AGENTS_HOME/agents/ai-vulnerability-monitor.md" ]]
[[ -f "$AGENTS_HOME/agents/legal-content-reviewer.md" ]]
[[ -f "$AGENTS_HOME/agents/sales.md" ]]
[[ -f "$AGENTS_HOME/agents/seo-researcher.md" ]]
[[ -f "$AGENTS_HOME/skills/security-gate/SKILL.md" ]]
[[ -f "$AGENTS_HOME/orchestration/protocol.md" ]]
[[ -x "$AGENTS_HOME/tools/team/team.sh" ]]
[[ -f "$AGENTS_HOME/.ecosystem-state.json" ]]
[[ -f "$AGENTS_HOME/local-models/mlx-local-runtime/README.md" ]]
[[ -f "$AGENTS_HOME/catalog.schema.json" ]]

"$AGENTS_HOME/tools/team/team.sh" --home "$AGENTS_HOME" validate-catalog
"$AGENTS_HOME/tools/team/team.sh" --home "$AGENTS_HOME" recommend \
  --tags software,quality --output "$TEST_HOME/recommendation.json"
"$AGENTS_HOME/tools/team/team.sh" --home "$AGENTS_HOME" plan \
  --goal "Ship a tested installer" --tags software,quality \
  --output "$TEST_HOME/plan.json"
"$AGENTS_HOME/tools/team/team.sh" --home "$AGENTS_HOME" task \
  --task-id task-001 --agent engineer --title "Improve installer" \
  --objective "Implement a bounded installer improvement" \
  --scope scripts/install.sh --recommend-skill software-delivery \
  --accept "Focused tests pass" --output "$TEST_HOME/task.json"
"$AGENTS_HOME/tools/team/team.sh" --home "$AGENTS_HOME" validate task "$TEST_HOME/task.json"
"$AGENTS_HOME/tools/team/team.sh" --home "$AGENTS_HOME" validate result \
  "$AGENTS_HOME/orchestration/templates/result.json"

HOME="$TEST_USER_HOME" "$ROOT/scripts/connect.sh" --host codex --host claude --host gemini --host sourcecraft --host kimi --host koda >/dev/null
[[ -f "$TEST_USER_HOME/.codex/agents/ceo.toml" ]]
[[ -f "$TEST_USER_HOME/.claude/agents/engineer.md" ]]
[[ -f "$TEST_USER_HOME/.gemini/agents/marketer.md" ]]
[[ -f "$TEST_USER_HOME/.config/opencode/agents/seo-researcher.md" ]]
[[ -f "$TEST_USER_HOME/.codeassistant/rules/agent-ecosystem.md" ]]
grep -q 'skill-router' "$TEST_USER_HOME/.claude/agents/engineer.md"
grep -q 'Independently select all relevant skills' "$TEST_USER_HOME/.gemini/agents/marketer.md"
grep -q 'scan compact' "$TEST_USER_HOME/.codex/agents/engineer.toml"
grep -q '^description: "' "$TEST_USER_HOME/.config/opencode/agents/seo-researcher.md"
grep -qx 'kimi' "$AGENTS_HOME/.ecosystem-hosts"
if grep -q 'Read the installed catalog' "$TEST_USER_HOME/.claude/agents/engineer.md"; then
  printf 'specialist wrapper unexpectedly preloads the full catalog\n' >&2
  exit 1
fi
if grep -q 'skill-router' "$TEST_USER_HOME/.claude/agents/security-reviewer.md"; then
  printf 'security reviewer unexpectedly preloaded optional skills\n' >&2
  exit 1
fi
if grep -q 'activate_skill' "$TEST_USER_HOME/.gemini/agents/security-reviewer.md"; then
  printf 'security reviewer unexpectedly received skill activation\n' >&2
  exit 1
fi
if contains_literal '"name":"design-master"' "$ROOT/catalog/catalog.json" || \
  contains_literal '"name":"team-lead"' "$ROOT/catalog/catalog.json"; then
  printf 'replaced agent remains in the canonical catalog\n' >&2
  exit 1
fi

if "$ROOT/scripts/install.sh" --profile core >/dev/null 2>&1; then
  :
else
  printf 'idempotent install failed\n' >&2
  exit 1
fi

printf 'personal rules\n' > "$AGENTS_HOME/AGENTS.md"
if "$ROOT/scripts/install.sh" --profile core >/dev/null 2>&1; then
  printf 'conflicting managed file was not reported\n' >&2
  exit 1
fi
grep -q '^personal rules$' "$AGENTS_HOME/AGENTS.md"

python3 "$ROOT/scripts/state.py" matches \
  --state "$AGENTS_HOME/.ecosystem-state.json" \
  --id skill:natural-writing \
  --path "$AGENTS_HOME/skills/natural-writing"

printf 'local customization\n' >> "$AGENTS_HOME/skills/natural-writing/SKILL.md"
if "$ROOT/scripts/install.sh" --profile core --no-root-files >/dev/null 2>&1; then
  printf 'modified managed skill was not reported as a conflict\n' >&2
  exit 1
fi
grep -q '^local customization$' "$AGENTS_HOME/skills/natural-writing/SKILL.md"
if "$ROOT/scripts/install.sh" --profile core --no-root-files --force >/dev/null 2>&1; then
  printf 'force overwrote or accepted a user-modified managed skill\n' >&2
  exit 1
fi
grep -q '^local customization$' "$AGENTS_HOME/skills/natural-writing/SKILL.md"

rm "$AGENTS_HOME/AGENTS.md"
"$ROOT/scripts/install.sh" --component skill:quality-review --no-root-files >/dev/null
[[ ! -e "$AGENTS_HOME/AGENTS.md" ]]

printf 'personal rules\n' > "$AGENTS_HOME/AGENTS.md"
"$ROOT/scripts/install.sh" --component skill:quality-review --force \
  --preserve-agents-file >/dev/null
grep -q '^personal rules$' "$AGENTS_HOME/AGENTS.md"

if [[ -n "$PORTABILITY_PID" ]]; then
  if ! wait "$PORTABILITY_PID"; then
    PORTABILITY_PID=""
    cat "$TEST_HOME/portability.log" >&2
    exit 1
  fi
  PORTABILITY_PID=""
  cat "$TEST_HOME/portability.log"
fi

if [[ -n "$WORKSPACE_PID" ]]; then
  if ! wait "$WORKSPACE_PID"; then
    WORKSPACE_PID=""
    cat "$TEST_HOME/workspace.log" >&2
    exit 1
  fi
  WORKSPACE_PID=""
  cat "$TEST_HOME/workspace.log"
fi

# Copies are verbatim, so generated bytecode must never appear in the source tree.
if find "$ROOT/library" "$ROOT/scripts" "$ROOT/tests" -name '__pycache__' -print -quit | grep -q .; then
  printf 'the test run left bytecode caches inside the repository\n' >&2
  exit 1
fi

printf 'All tests passed.\n'
