agent:marketer
skill:market-research
skill:audience-segmentation
skill:customer-interviews
skill:positioning
skill:messaging
skill:offer-design
skill:brand-voice
skill:copywriting
skill:copy-editing
skill:landing-page
skill:email-strategy
skill:welcome-sequence
skill:nurture-sequence
skill:launch-email
skill:cold-email
skill:newsletter
skill:ad-strategy
skill:ad-creative
skill:content-strategy
skill:social-content
skill:lead-magnet
skill:cro-audit
skill:campaign-launch
